### ISSUE TITLE
Lombok should not be a transitive dependency

### ISSUE THREAD

**Issue by reda-alaoui** [ununbium/HateoasUtils#10]
Executing mvn dependency:tree, I have:
```
[INFO] +- rocks.spiffy:HateoasUtils:jar:1.1.0:compile
[INFO] |  \- org.projectlombok:lombok:jar:1.16.4:compile
```

I think Lombok should not be leaked to the consumers.

**Comment by ununbium** [comment]
Good point, 

Furthermore Lombok isn't used heavily in the project anyway. I'll just remove it as part of 1.2.0

Thanks,
Andy

**Comment by reda-alaoui** [comment]
Thank you !
