### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by reda-alaoui** [ununbium/HateoasUtils#5]
Hello,

Could you release to maven central?

**Comment by ununbium** [comment]
Thanks for flagging this Réda. I've updated the project in preparation for release, just waiting on Sonatype OSSRH project set up, should be up there in the next few days.

**Comment by ununbium** [comment]
Hi Réda, 

Version 1.1.0 has been released via maven central. Here's the dependency;

```
<dependency>
    <groupId>rocks.spiffy</groupId>
    <artifactId>HateoasUtils</artifactId>
    <version>1.1.0</version>
</dependency>
```


Cheers,
Andy

**Comment by reda-alaoui** [comment]
Thanks @ununbium !
